### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by Siddhant-K-code** [gjariwala9/GST_Billing_System#2]
While clicking on menu to change to register from login, it gets lagged and doesn't responds further.

**Comment by Siddhant-K-code** [comment]
Why didn't you respond ?

**Comment by gjariwala9** [comment]
I did on linkedin.

**Comment by gjariwala9** [comment]
Hey,
Thanks for pointing out the error in my GST_Billing_System repo. I have corrected the code and updated it on GitHub along with the installation and how to run the code guide.
If you like the the application please do star it and fork it.
